/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: Ricardo Garnica (https://sketchfab.com/rjgarnicap)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-globe-atlas-cd178e25a0e6436380b15fc1539a25f2
Title: Earth Globe - Atlas
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function EarthIcon(props) {
  const { nodes, materials } = useGLTF("/earth.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.heightmap_ref_group}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.heightmap_ref_group}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/earth.gltf");
